# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Welcome to Jekyll!
title: Miller Brothers Team Leagues
email: jeffmiller00@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A league where you draft NFL teams and score it by the number of wins the
  team gets during the season.
keywords: Miller,brothers,fantasy,nfl,nba
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.millerteamleague.com" # the base hostname & protocol for your site, e.g. http://example.com
# img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Jeff Miller  # Be used at blog posts' author.
  first_name: Jeff  # Be used at index page about me section.
  last_name: Miller  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: jeffmiller00  # Leave blank if you don't have now
  linkedin_id: jeffmiller00 # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username: couchchamp  # Leave blank if you don't have now
  email: jeffmiller00@gmail.com  # Leave blank if you don't have now
  cv:   # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Introduce myself will be here.  # Describe yourself.

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: off  # index page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8
timezone: America/Chicago

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
